module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@shared/(.*)$': '<rootDir>/../../shared/$1',
    '\\.css$': '<rootDir>/tests/__mocks__/fileMock.js',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|@react-native|expo|@expo|@unimodules|nativewind|@gluestack-ui|@gluestack-style)',
  ],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    'app/**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/jest.setup.ts',
    '!**/__tests__/**',
    '!**/tests/**',
    '!src/ui/components/index.ts',
    '!src/ui/components/AppText.tsx',
    '!app/_layout.tsx',
    '!src/i18n/**',
    '!src/lib/**',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'text-summary', 'lcov', 'html'],
  coverageThreshold: {
    global: { statements: 55, branches: 40, functions: 55, lines: 55 },
    'src/features/**/*.{ts,tsx}': { statements: 50, branches: 30, functions: 55, lines: 50 },
    'src/data/hooks/**/*.{ts,tsx}': { statements: 85, branches: 65, functions: 80, lines: 85 },
    'src/stores/**/*.{ts,tsx}': { statements: 90, branches: 85, functions: 90, lines: 90 },
    'src/ui/utils/**/*.{ts,tsx}': { statements: 90, branches: 85, functions: 90, lines: 90 },
    'src/ui/components/**/*.{ts,tsx}': { statements: 80, branches: 50, functions: 80, lines: 80 },
    'app/**/*.{ts,tsx}': { statements: 50, branches: 0, functions: 50, lines: 50 },
  },
}
